### ISSUE TITLE
Checking for higher occurance

### ISSUE THREAD

**Issue by westwq** [MAD-2020/mad-practical-1-java-AwJoey#2]
https://github.com/MAD-2020/mad-practical-1-java-AwJoey/blob/15da77c85cf01bc471c00dd127f0772596f6d976/Question5.java#L53

You are v close to getting 100% correct.
Your comparision is checking for x-1 > y
test with 5,2,2,3,3,3

**Comment by AwJoey** [comment]
Ok I corrected it already. Thank you Mr Wesley!
